package ui;

import interfaces.VistaOperarMesaCrupier;
import Controladores.ControladorOperarMesaCrupier;
import componente.PanelRuleta;
import dominio.Crupier;
import dominio.Jugador;
import dominio.MecanismoSorteo;
import dominio.Mesa;
import dominio.Bola;
import dominio.Ronda;
import dominio.TipoApuesta;
import interfaces.Renderizable;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author digregor
 */
public class OperarMesaCrupier extends javax.swing.JFrame implements VistaOperarMesaCrupier {

    private ControladorOperarMesaCrupier controlador;
    private TipoApuesta[] tipoApuesta;
    int apuestaRojo = 0;
    private Mesa mesa;
    

    /**
     * Creates new form NewJFrame
     */
    public OperarMesaCrupier(Crupier crupier, TipoApuesta[] tiposApuesta) {
        this.controlador = new ControladorOperarMesaCrupier(this, crupier);
        this.tipoApuesta = tiposApuesta;
        this.mesa = controlador.getMesaAsignada();
        initComponents();
        inhabilitarComponentes();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r = new componente.PanelRuleta();
        jLabel1 = new javax.swing.JLabel();
        txtBceMesa = new javax.swing.JTextField();
        lbPesos = new javax.swing.JLabel();
        txtRonda = new javax.swing.JTextField();
        lbRonda = new javax.swing.JLabel();
        lbRuleta = new javax.swing.JLabel();
        lbPesos2 = new javax.swing.JLabel();
        txtRuleta = new javax.swing.JTextField();
        btnCerrarMesa = new javax.swing.JButton();
        lbApuestas = new javax.swing.JLabel();
        txtApuestas = new javax.swing.JTextField();
        lbMonto = new javax.swing.JLabel();
        txtApuestasRonda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbEfectos = new javax.swing.JComboBox<>();
        btnLanzarPagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabla2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListUltimosLanzamientos = new javax.swing.JList<>();
        txtUltimoNumeroSorteado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("$ -");

        txtBceMesa.setEditable(false);
        txtBceMesa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBceMesa.setForeground(new java.awt.Color(255, 51, 51));
        txtBceMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBceMesaActionPerformed(evt);
            }
        });

        lbPesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/pesos.png"))); // NOI18N

        txtRonda.setEditable(false);
        txtRonda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbRonda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbRonda.setText("Ronda #");

        lbRuleta.setText("Ruleta #");

        lbPesos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/ruleta.png"))); // NOI18N

        txtRuleta.setEditable(false);

        btnCerrarMesa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrarMesa.setText("Cerrar mesa");
        btnCerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMesaActionPerformed(evt);
            }
        });

        lbApuestas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbApuestas.setText("Apuestas:");

        txtApuestas.setEditable(false);
        txtApuestas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbMonto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMonto.setText("Monto$");

        txtApuestasRonda.setEditable(false);
        txtApuestasRonda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Aplicación Crupier  -  Operar Ruleta");

        cbEfectos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEfectos.setToolTipText("");
        cbEfectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEfectosActionPerformed(evt);
            }
        });

        btnLanzarPagar.setText("Lanzar/Pagar");
        btnLanzarPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarPagarActionPerformed(evt);
            }
        });

        jTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ronda", "Bce Anterior", "Apuestas", "Recolección", "Liquidación", "Bce Posterior"
            }
        ));
        jTabla1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTabla1);

        jTabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Jugador", "Saldo"
            }
        ));
        jScrollPane2.setViewportView(jTabla2);

        jScrollPane3.setViewportView(jListUltimosLanzamientos);

        txtUltimoNumeroSorteado.setEditable(false);

        jLabel3.setText("Último número sorteado");

        jLabel4.setText("Últimos Lanzamientos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbApuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBceMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtApuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(lbMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtApuestasRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbEfectos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPesos2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnCerrarMesa))
                                    .addComponent(btnLanzarPagar)))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(txtUltimoNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbPesos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtBceMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApuestasRonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbApuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbPesos2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCerrarMesa)))
                        .addGap(8, 8, 8)
                        .addComponent(btnLanzarPagar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(cbEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUltimoNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBceMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBceMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBceMesaActionPerformed

    private void btnLanzarPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarPagarActionPerformed
        lanzarPagar();
    }//GEN-LAST:event_btnLanzarPagarActionPerformed

    private void btnCerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMesaActionPerformed
        cerrarMesa();
    }//GEN-LAST:event_btnCerrarMesaActionPerformed

    private void cbEfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEfectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEfectosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarMesa;
    private javax.swing.JButton btnLanzarPagar;
    private javax.swing.JComboBox<String> cbEfectos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<Integer> jListUltimosLanzamientos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabla1;
    private javax.swing.JTable jTabla2;
    private javax.swing.JLabel lbApuestas;
    private javax.swing.JLabel lbMonto;
    private javax.swing.JLabel lbPesos;
    private javax.swing.JLabel lbPesos2;
    private javax.swing.JLabel lbRonda;
    private javax.swing.JLabel lbRuleta;
    private componente.PanelRuleta r;
    private javax.swing.JTextField txtApuestas;
    private javax.swing.JTextField txtApuestasRonda;
    private javax.swing.JTextField txtBceMesa;
    private javax.swing.JTextField txtRonda;
    private javax.swing.JTextField txtRuleta;
    private javax.swing.JTextField txtUltimoNumeroSorteado;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        habilitarComponentes();
        controlador.obtenerDatos();
        //controlador.listarJugadoresConSuSaldo();
        //controlador.ultimosLanzamientos();
        //controlador.ultimoNumeroSorteado();
        //controlador.listarRondasConSuInformacion();
    }

    @Override
    public void mostrarDatos(int saldoMesa, int ronda, int numeroMesa, ArrayList<MecanismoSorteo> efectos) {
        txtBceMesa.setText(saldoMesa + "");
        txtRonda.setText(ronda + "");
        txtRuleta.setText(numeroMesa + "");
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (MecanismoSorteo e : efectos) {
            model.addElement(e.getNombre());
        }
        cbEfectos.setModel(model);
    }
    

    private void lanzarPagar() {
        int numeroDeRonda = Integer.parseInt(txtRonda.getText());
        int balanceSaldo = Integer.parseInt(txtBceMesa.getText());
        //int montoTotalApostado = Integer.parseInt(txtApuestasRonda.getText());
        //int cantidadDeApuestas = Integer.parseInt(txtApuestas.getText());
        int montoTotalApostado = 0;
        int cantidadDeApuestas = 0;
        String mecanismo = (String) cbEfectos.getSelectedItem();
        controlador.lanzarPagar(numeroDeRonda, balanceSaldo, montoTotalApostado, cantidadDeApuestas, mesa, mecanismo);
    }

    @Override
    public void mostrarBola(Bola bolaSorteada) {
        txtUltimoNumeroSorteado.setText(bolaSorteada.getNumero() + "");
    }

    private void cerrarMesa() {
        controlador.cerrarMesa();
    }

    private class Detalle implements ListCellRenderer<Renderizable> {

        @Override
        public Component getListCellRendererComponent(JList<? extends Renderizable> list, Renderizable value, int index, boolean isSelected, boolean cellHasFocus) {
            JLabel label = new JLabel();
            label.setText(value.getRenderDetail());
            return label;
        }
    }

    private void inhabilitarComponentes() {
        r.setVisible(PanelRuleta.MAYOR, false);
        r.setVisible(PanelRuleta.MENOR, false);
        r.setVisible(PanelRuleta.COMPUESTO, false);
        r.setVisible(PanelRuleta.PRIMO, false);
        r.setVisible(PanelRuleta.IMPAR, false);
        r.setVisible(PanelRuleta.PAR, false);
        r.setVisible(PanelRuleta.PRIMERA_COLUMNA, false);
        r.setVisible(PanelRuleta.SEGUNDA_COLUMNA, false);
        r.setVisible(PanelRuleta.TERCERA_COLUMNA, false);
        r.setVisible(PanelRuleta.ROJO, false);
        r.setVisible(PanelRuleta.NEGRO, false);
        r.setVisible(PanelRuleta.PRIMERA_DOCENA, false);
        r.setVisible(PanelRuleta.SEGUNDA_DOCENA, false);
        r.setVisible(PanelRuleta.TERCERA_DOCENA, false);
    }

    private void habilitarComponentes() {
        for (TipoApuesta ta : tipoApuesta) {
            switch (ta.getNombre()) {
                case "Colores":
                    r.setVisible(PanelRuleta.ROJO, true);
                    r.setVisible(PanelRuleta.NEGRO, true);
                    break;
                case "Docena":
                    r.setVisible(PanelRuleta.PRIMERA_DOCENA, true);
                    r.setVisible(PanelRuleta.SEGUNDA_DOCENA, true);
                    r.setVisible(PanelRuleta.TERCERA_DOCENA, true);
                    break;
                default:
                    break;
            }
        }
    }
    
  

    @Override
    public void salir() {
        dispose();
    }
    
    @Override
    public void listarJugadoresConSuSaldo(ArrayList<Jugador> jugadores) {

        DefaultTableModel modelo = (DefaultTableModel) jTabla2.getModel();
        modelo.setRowCount(0); // Limpia todas las filas existentes en la tabla

        for (Jugador jugador : jugadores) {
            String nombreJugador = jugador.getNombre(); 
            double saldo = jugador.getSaldoInicial(); 
            modelo.addRow(new Object[]{nombreJugador, saldo});
        }
        
    }
    
    @Override
    public void listarRondasConSuInformacion(ArrayList<Ronda> rondas) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTabla1.getModel();
        modelo.setRowCount(0); // Limpia todas las filas existentes en la tabla
        
        int balanceAnterior = 0; // Inicializa el balance anterior en 0

        for (Ronda r : rondas) {
            int numeroRonda = r.getNumero(); 
            //int balanceAnterior = r.getBalanceAnteriorAlSorteo();
            int montoTotalDeApuestas = r.montoTotalDeLasApuestas(); 
            int montoTotalApuestasPerdidas = r.montoTotalApuestasPerdidasRecoleccion();
            int montoTotalDeApuestasPagadas = r.montoTotalApuestasPagadasLiquidacion();
            int balancePosteriorAlSorteo = r.getBalanceSaldo();
            modelo.addRow(new Object[]{numeroRonda, balanceAnterior, montoTotalDeApuestas, montoTotalApuestasPerdidas, montoTotalDeApuestasPagadas, balancePosteriorAlSorteo });
        
            // Actualiza el balance anterior para la próxima ronda
            balanceAnterior = balancePosteriorAlSorteo;

        }
        
    }

    
    //PARTE DE ULTIMOS LANZAMIENTOS:
    
    @Override
    public void ultimosLanzamientos(ArrayList<Integer> ultimosLanzamientos) {
        
        DefaultListModel<Integer> lista = new DefaultListModel<>();

        for (Integer numero : ultimosLanzamientos) {
            lista.addElement(numero);
        }

        jListUltimosLanzamientos.setModel(lista);
    }
    
    @Override
    public void ultimoNumeroSorteado(int ultimoNumero) {
        txtUltimoNumeroSorteado.setText(String.valueOf(ultimoNumero));
    }
    
    @Override
    public void pausarRuleta(){
        r.pausar();
    }
    
    @Override
    public void reanudarRuleta(){
        r.reanudar();
    }

}
